--tao csdl
CREATE DATABASE QuanLyNhanSu
GO
--su dung csdl
USE QuanLyNhanSu
GO
--tao bang NHAN VIEN
CREATE TABLE NHANVIEN
(
	MaNV VARCHAR(20) PRIMARY KEY, HoTen NVARCHAR(50), NgaySinh DATE, QueQuan NVARCHAR(100), GioiTinh NCHAR(5),
	DanToc NVARCHAR(20),SDT INT ,MaPB VARCHAR(20),MaCV VARCHAR(20), MaTDHV VARCHAR(20), BacLuong FLOAT,
	NgayTangLuong DATE
)
GO

--tao bang PHONG BAN
CREATE TABLE PHONGBAN
(
	MaPB VARCHAR(20) PRIMARY KEY, TenPB NVARCHAR(30),DiaChi NVARCHAR(20),SDTPB INT
)
GO

--tao bang CHUC VU
CREATE TABLE CHUCVU
(
	MaCV VARCHAR(20) PRIMARY KEY, TenCV NVARCHAR(30)
)
GO

--tao bang TRINH DO HOC VAN
CREATE TABLE TRINHDOHOCVAN
(
	MaTDHV VARCHAR(20) PRIMARY KEY, TenTDHV NVARCHAR(20), ChuyenNganh NVARCHAR(30)
)
GO

--tao bang LUONG
CREATE TABLE LUONG
(
	BacLuong FLOAT PRIMARY KEY, LuongCB INT , HSLUONG FLOAT, HSPhuCap INT
)
GO

--tao bang HOP DONG LAO DONG
CREATE TABLE HOPDONGLAODONG
(
	MaHD VARCHAR (20) PRIMARY KEY, MaNV VARCHAR (20), LoaiHD NVARCHAR(20), NgayBatDau DATE, NgayKetThuc DATE 
)
GO

--xoa bang 
DROP TABLE HOPDONGLAODONG
DROP TABLE LUONG
DROP TABLE NHANVIEN
DROP TABLE PHONGBAN
DROP TABLE CHUCVU
DROP TABLE TRINHDOHOCVAN

--TAO KHOA NGOAI
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_PB_NV FOREIGN KEY (MaPB) REFERENCES  PHONGBAN(MaPB)
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_CV_NV FOREIGN KEY (MaCV) REFERENCES  CHUCVU(MaCV)
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_TDHV_NV FOREIGN KEY (MaTDHV) REFERENCES  TRINHDOHOCVAN(MaTDHV)
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_LUONG_NV FOREIGN KEY (BacLuong) REFERENCES  LUONG(BacLuong)
ALTER TABLE HOPDONGLAODONG ADD CONSTRAINT FK_HDLD_NV FOREIGN KEY (MaNV) REFERENCES  NHANVIEN(MaNV)

--tao storeprocedure
--Lay danh sach nhan vien
CREATE PROC sp_LayDSNV
AS
SELECT * FROM NHANVIEN
GO
---LAY DANH SACH CHUC VU---
CREATE PROC SP_LAYDANHSACHCHUCVU
 AS
 SELECT * FROM CHUCVU
 GO
 ---LAY DANH SACH TRINH DO HOC VAN---
 CREATE PROC SP_LAYDANHSACHTRINHDOHOCVAN
 AS
 SELECT * FROM TRINHDOHOCVAN
 GO
--------------






--THEM NV
CREATE PROC sp_ThemNV
(
	@MaNV VARCHAR(20), @HoTen NVARCHAR(50), @NgaySinh DATE, @QueQuan NVARCHAR(100), @GioiTinh NCHAR(5),
	@DanToc NVARCHAR(20),@SDT INT ,@MaPB VARCHAR(20),@MaCV VARCHAR(20), @MaTDHV VARCHAR(20), @BacLuong FLOAT,
	@NgayTangLuong DATE 
)
AS
INSERT INTO NHANVIEN
(
	MaNV , HoTen , NgaySinh, QueQuan , GioiTinh ,DanToc ,SDT  ,MaPB ,MaCV , MaTDHV , BacLuong ,NgayTangLuong
)
VALUES (@MaNV , @HoTen, @NgaySinh , @QueQuan , @GioiTinh ,@DanToc ,@SDT  ,@MaPB ,@MaCV , @MaTDHV , @BacLuong ,@NgayTangLuong )
EXEC sp_ThemNV '17001TT','Tran Dang Khoa', '12/20/1999','Binh Thuan', 'Nam','Kinh',0364143265,'KT001','GD','aaa',3.5,'12/20/2000'
GO

--Sua Nhan Vien---
CREATE PROCEDURE sp_SuaNV
(
	@MaNV VARCHAR(20), @HoTen NVARCHAR(50), @NgaySinh DATE, @QueQuan NVARCHAR(100), @GioiTinh NCHAR(5),
	@DanToc NVARCHAR(20),@SDT INT ,@MaPB VARCHAR(20),@MaCV VARCHAR(20), @MaTDHV VARCHAR(20), @BacLuong FLOAT,
	@NgayTangLuong DATE
)
AS
    UPDATE NHANVIEN
    SET MaNV = @MaNV , HoTen = @HoTen ,NgaySinh = @NgaySinh,QueQuan = @QueQuan, GioiTinh = @GioiTinh, DanToc = @DanToc,SDT= @SDT, MaPB = @MaPB,
    MaCV = @MaCV, MaTDHV = @MaTDHV, BacLuong = @BacLuong, NgayTangLuong = @NgayTangLuong
    WHERE MaNV = @MaNV
    
--TESTSUA NHAN VIEN--- 
EXEC sp_SuaNV '17001TT','Tran Dang Khoa', '01/01/1999','Binh Thuan', 'Nam','Kinh',0364143265,'KT001','GD','ccc',3.5,'12/20/2000'
GO

--XEM LAI SAU KHI SUA
EXEC sp_LayDSNV
GO

--XOA PROCEDIRE
DROP PROC sp_ThemNV

--THEM Luong
CREATE PROC sp_ThemLuong
(
	@BacLuong FLOAT , @LuongCB INT , @HSLUONG FLOAT, @HSPhuCap INT
)
AS
INSERT INTO LUONG
(
	BacLuong, LuongCB  , HSLUONG , HSPhuCap 
)
VALUES (@BacLuong , @LuongCB, @HSLUONG, @HSPhuCap)
EXEC sp_ThemLuong 3.5, 20000,2.5,1500

--THEM Hop Dong Lao Dong
CREATE PROC sp_ThemHDLD
(
	@MaHD VARCHAR (20) , @MaNV VARCHAR (20), @LoaiHD NVARCHAR(20), @NgayBatDau DATE, @NgayKetThuc DATE 
)
AS
INSERT INTO HOPDONGLAODONG
(
	MaHD  , MaNV , LoaiHD , NgayBatDau , NgayKetThuc  
)
VALUES (@MaHD , @MaNV, @LoaiHD, @NgayBatDau, @NgayKetThuc)
EXEC sp_ThemHDLD 'DH', '17001TT', 'Dai han', '12/20/2018','12/20/2023'
--LAY RA DANH SACH
EXEC sp_LayDSNV
--lay danh sach phong ban
EXEC sp_LayDSPB
----------------
 
GO
---SP_XOA NHAN VIEN---
CREATE PROC sp_XoaMotNhanVien @MaNV VARCHAR(20)
AS
  DELETE NHANVIEN WHERE MaNV = @MaNV
GO
---TEST XOA
EXEC sp_XoaMotNhanVien '17001TT'
GO
---XEM LAI KHI XOA---
EXEC sp_LayDSNV
GO
---Tao storeprocedure PHONG BAN---
---SP_LAY DANH SACH PHONG BAN---
CREATE PROC SP_LAYDANHSACHPHONGBAN
  AS
   SELECT * FROM PHONGBAN
GO
---SP_THEM PHONG BAN----
CREATE PROC SP_THEMPHONGBAN(@MaPB VARCHAR(20), @TenPB NVARCHAR(30),@DiaChi NVARCHAR(20),@SDTPB INT)
   AS 
    INSERT INTO PHONGBAN(MaPB , TenPB , DiaChi , SDTPB)
    VALUES(@MaPB , @TenPB , @DiaChi , @SDTPB)
GO
---TEST THEM PHONG BAN---
EXEC SP_THEMPHONGBAN N'PBBV', N'Phòng Bảo Vệ',N'Thủ Đức', 0962223453
EXEC SP_THEMPHONGBAN N'PBHG', N'PhòngGDGFD Vệ',N'Thủ Đức', 0962223453
EXEC SP_THEMPHONGBAN N'PBGH', N'Phòng DFGD Vệ',N'Thủ Đức', 0962223453
GO
---XEM KHI DA THEM---
EXEC SP_LAYDANHSACHPHONGBAN
GO
---SP_SUA PHONG BAN---
CREATE PROCEDURE SP_SUAPHONGBAN(@MaPB VARCHAR(20),@TenPB NVARCHAR(30),@DiaChi NVARCHAR(20),@SDTPB INT)
   AS
    UPDATE PHONGBAN
    SET TenPB=@TenPB , DiaChi=@DiaChi ,SDTPB = @SDTPB
    WHERE MaPB = @MaPB
GO
---TESTSUA PHONG BAN--- 
EXEC SP_SUAPHONGBAN N'PBBV', N'Phòng Bảo Vệ',N'HAI PHONG', 0962223453
GO
---XEM LAI KHI SUA---
EXEC SP_LAYDANHSACHPHONGBAN
GO
---SP_XOA PHONG BAN DUA VAO MAPB---
CREATE PROC SP_XOAMOTPHONGBAN @MaPB VARCHAR(20)
AS
  DELETE PHONGBAN WHERE MaPB = @MaPB
GO
---TEST XOA
EXEC SP_XOAMOTPHONGBAN N'PBBV'
GO
---XEM LAI KHI XOA---
EXEC SP_LAYDANHSACHPHONGBAN

GO
----CHEN DU LIEU CHO BANG CHUC VU----
INSERT INTO CHUCVU VALUES('TKCV', N'Thư Kí')
INSERT INTO CHUCVU VALUES('GDCV', N'GIÁM ĐỐC')
INSERT INTO CHUCVU VALUES('KTCV', N'Kế Toán')
INSERT INTO CHUCVU VALUES('TTCV', N'Tiếp Tân')
INSERT INTO CHUCVU VALUES('QLCV', N'Quản Lý')
GO


---SP_THEM CHUC VU---
CREATE PROC SP_THEMCHUCVU(@MaCV VARCHAR(20), @TenCV NVARCHAR(30))
   AS 
    INSERT INTO CHUCVU(MaCV, TenCV)
    VALUES(@MaCV , @TenCV)
GO
---TEST THEM CHUC VU---
EXEC SP_THEMCHUCVU 'BVCV', N'Bảo Vệ'
GO
---XEM KHI DA THEM---
EXEC SP_LAYDANHSACHCHUCVU
GO
---SP_SUA CHUC VU---
CREATE PROCEDURE SP_SUACHUCVU(@MaCV VARCHAR(20), @TenCV NVARCHAR(30))
   AS
    UPDATE CHUCVU
    SET TenCV=@TenCV
    WHERE MaCV = @MaCV
---TEST  SUA CHUC VU--- 
GO
EXEC SP_SUACHUCVU 'BVCV', N'NHANSU'
GO
---XEM LAI KHI SUA---
EXEC SP_LAYDANHSACHCHUCVU
GO
---SP_XOA CHUC VU DUA VAO MAPB---
CREATE PROC SP_XOAMOTCHUCVU @MaCV VARCHAR(20)
AS
  DELETE CHUCVU WHERE MaCV = @MaCV
GO
---TEST XOA
EXEC SP_XOAMOTCHUCVU 'BVCV'
GO
---XEM LAI KHI XOA---
EXEC SP_LAYDANHSACHCHUCVU

 GO



 ---SP_THEMTRINHDOHOCVAN---
CREATE PROC SP_THEMTRINHDOHOCVAN(@MaTDHV VARCHAR(20), @TenTDHV NVARCHAR(20), @ChuyenNganh NVARCHAR(30))
   AS 
    INSERT INTO TRINHDOHOCVAN(MaTDHV , TenTDHV, ChuyenNganh)
    VALUES(@MaTDHV , @TenTDHV, @ChuyenNganh)
GO
 ---TEST THEMTRINHDOHOCVAN---
EXEC SP_THEMTRINHDOHOCVAN 'TC_TDHV',N'Trung Cấp',N'Cơ Điện'
GO
---XEM KHI DA THEM---
EXEC SP_LAYDANHSACHTRINHDOHOCVAN
GO
---SP_SUA TRINHDOHOCVAN---
CREATE PROCEDURE SP_SUATRINHDOHOCVAN(@MaTDHV VARCHAR(20), @TenTDHV NVARCHAR(20), @ChuyenNganh NVARCHAR(30))
   AS
    UPDATE TRINHDOHOCVAN
    SET TenTDHV =@TenTDHV, ChuyenNganh = @ChuyenNganh
    WHERE MaTDHV = @MaTDHV
GO
---TESTSUA TRINHDOHOCVAN--- 
EXEC SP_SUATRINHDOHOCVAN 'CD_TDHV',N'Đại Học',N'Ô Tô'
GO
---XEM LAI KHI SUA---
EXEC SP_LAYDANHSACHTRINHDOHOCVAN
GO
---SP_XOA TRINH DO HOC VAN DUA VAO MaTDHV---
CREATE PROC SP_XOAMOTTRINHDOHOCVAN @MaTDHV VARCHAR(20)
AS
  DELETE TRINHDOHOCVAN WHERE MaTDHV = @MaTDHV
GO
---TEST XOA
EXEC SP_XOAMOTTRINHDOHOCVAN 'CD_TDHV'
GO
---XEM LAI KHI XOA---
EXEC SP_LAYDANHSACHTRINHDOHOCVAN
