--tao csdl
CREATE DATABASE QuanLyNhanSu
GO
--su dung csdl
USE QuanLyNhanSu
GO
--tao bang NHAN VIEN
CREATE TABLE NHANVIEN
(
	MaNV VARCHAR(20) PRIMARY KEY, HoTen NVARCHAR(50), NgaySinh DATE, QueQuan NVARCHAR(100), GioiTinh NCHAR(5),
	DanToc NVARCHAR(20),SDT INT ,MaPB VARCHAR(20),MaCV VARCHAR(20), MaTDHV VARCHAR(20), BacLuong FLOAT,
	NgayTangLuong DATE
)
GO
--tao bang PHONG BAN
CREATE TABLE PHONGBAN
(
	MaPB VARCHAR(20) PRIMARY KEY, TenPB NVARCHAR(30),DiaChi NVARCHAR(20),SDTPB INT
)
GO
--tao bang CHUC VU
CREATE TABLE CHUCVU
(
	MaCV VARCHAR(20) PRIMARY KEY, TenCV NVARCHAR(30)
)
GO
--tao bang TRINH DO HOC VAN
CREATE TABLE TRINHDOHOCVAN
(
	MaTDHV VARCHAR(20) PRIMARY KEY, TenTDHV NVARCHAR(20), ChuyenNganh NVARCHAR(30)
)
GO
--tao bang LUONG
CREATE TABLE LUONG
(
	BacLuong FLOAT PRIMARY KEY, LuongCB INT , HSLUONG FLOAT, HSPhuCap INT
)
GO
--tao bang HOP DONG LAO DONG
CREATE TABLE HOPDONGLAODONG
(
	MaHD VARCHAR (20) PRIMARY KEY, MaNV VARCHAR (20), LoaiHD NVARCHAR(20), NgayBatDau DATE, NgayKetThuc DATE 
)
GO
--xoa bang 
DROP TABLE HOPDONGLAODONG
DROP TABLE LUONG
DROP TABLE NHANVIEN
DROP TABLE PHONGBAN
DROP TABLE CHUCVU
DROP TABLE TRINHDOHOCVAN
--TAO KHOA NGOAI
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_PB_NV FOREIGN KEY (MaPB) REFERENCES  PHONGBAN(MaPB)
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_CV_NV FOREIGN KEY (MaCV) REFERENCES  CHUCVU(MaCV)
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_TDHV_NV FOREIGN KEY (MaTDHV) REFERENCES  TRINHDOHOCVAN(MaTDHV)
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_LUONG_NV FOREIGN KEY (BacLuong) REFERENCES  LUONG(BacLuong)
ALTER TABLE HOPDONGLAODONG ADD CONSTRAINT FK_HDLD_NV FOREIGN KEY (MaNV) REFERENCES  NHANVIEN(MaNV)
--tao storeprocedure
--lay danh sach nhan vien
CREATE PROC sp_LayDSNV
AS
SELECT * FROM NHANVIEN
GO

DROP PROC sp_LayDSPB
--THEM NV
CREATE PROC sp_ThemNV
(
	@MaNV VARCHAR(20), @HoTen NVARCHAR(50), @NgaySinh DATE, @QueQuan NVARCHAR(100), @GioiTinh NCHAR(5),
	@DanToc NVARCHAR(20),@SDT INT ,@MaPB VARCHAR(20),@MaCV VARCHAR(20), @MaTDHV VARCHAR(20), @BacLuong FLOAT,
	@NgayTangLuong DATE 
)
AS
INSERT INTO NHANVIEN
(
	MaNV , HoTen , NgaySinh, QueQuan , GioiTinh ,DanToc ,SDT  ,MaPB ,MaCV , MaTDHV , BacLuong ,NgayTangLuong
)
VALUES (@MaNV , @HoTen, @NgaySinh , @QueQuan , @GioiTinh ,@DanToc ,@SDT  ,@MaPB ,@MaCV , @MaTDHV , @BacLuong ,@NgayTangLuong )
EXEC sp_ThemNV '17001TT','Tran Dang Khoa', '12/20/1999','Binh Thuan', 'Nam','Kinh',0364143265,'KT001','GD','aaa',3.5,'12/20/2000'
--XOA PROCEDIRE
DROP PROC sp_ThemNV	
	

--LAY RA DANH SACH
EXEC sp_LayDSNV
----------------

--SP_SUA NHAN VIEN---
CREATE PROCEDURE sp_SuaNV
(
	@MaNV VARCHAR(20), @HoTen NVARCHAR(50), @NgaySinh DATE, @QueQuan NVARCHAR(100), @GioiTinh NCHAR(5),
	@DanToc NVARCHAR(20),@SDT INT ,@MaPB VARCHAR(20),@MaCV VARCHAR(20), @MaTDHV VARCHAR(20), @BacLuong FLOAT,
	@NgayTangLuong DATE
)
AS
    UPDATE NHANVIEN
    SET MaNV = @MaNV , HoTen = @HoTen ,NgaySinh = @NgaySinh,QueQuan = @QueQuan, GioiTinh = @GioiTinh, DanToc = @DanToc,SDT= @SDT, MaPB = @MaPB,
    MaCV = @MaCV, MaTDHV = @MaTDHV, BacLuong = @BacLuong, NgayTangLuong = @NgayTangLuong
    WHERE MaNV = @MaNV
--TESTSUA NHAN VIEN--- 
EXEC sp_SuaNV '17001TT','Tran Dang Khoa', '01/01/1999','Binh Thuan', 'Nam','Kinh',0364143265,'KT001','GD','ccc',3.5,'12/20/2000'
GO
--XEM LAI KHI SUA
EXEC sp_LayDSNV
GO